// Generated by CoffeeScript 1.9.1
(function() {
  var GuestMetrics, Promise, debug;

  debug = require('debug')('XenAPI:GuestMetrics');

  Promise = require('bluebird');

  GuestMetrics = (function() {
    var session, xenAPI;

    session = void 0;

    xenAPI = void 0;


    /**
    * Construct GuestMetrics
    * @class
    * @param      {Object}   session - An instance of Session
    * @param      {Object}   guestmetrics - A JSON object representing this GuestMetrics
    * @param      {String}   opaqueRef - The OpaqueRef handle to this GuestMetrics
    * @param      {Object}   xenAPI - An instance of XenAPI
     */

    function GuestMetrics(_session, _guestmetrics, _opaqueRef, _xenAPI) {
      debug("constructor()");
      debug(_guestmetrics, _opaqueRef);
      if (!_session) {
        throw Error("Must provide `session`");
      }
      if (!_guestmetrics) {
        throw Error("Must provide `guestmetrics`");
      }
      if (!_opaqueRef) {
        throw Error("Must provide `opaqueRef`");
      }
      session = _session;
      xenAPI = _xenAPI;
      this.opaqueRef = _opaqueRef;
      this.uuid = _guestmetrics.uuid;
      this.networks = _guestmetrics.networks;
      this.os_version = _guestmetrics.os_version;
      this.memory = _guestmetrics.memory;
      this.disks = _guestmetrics.disks;
      this.last_updated = _guestmetrics.last_updated;
    }

    return GuestMetrics;

  })();

  module.exports = GuestMetrics;

}).call(this);
