// Generated by CoffeeScript 1.10.0
(function() {
  var Host_CPU, Promise, debug;

  debug = require('debug')('XenAPI:Host_CPU');

  Promise = require('bluebird');

  Host_CPU = (function() {
    var session, xenAPI;

    session = void 0;

    xenAPI = void 0;


    /**
    * Construct Host_CPU
    * @class
    * @param      {Object}   session - An instance of Session
    * @param      {Object}   host_cpu - A JSON object representing this host_cpu
    * @param      {String}   opaqueRef - The OpaqueRef handle to this host_cpu
    * @param      {Object}   xenAPI - An instance of XenAPI
     */

    function Host_CPU(_session, _cpu, _opaqueRef, _xenAPI) {
      debug("constructor()");
      debug(_cpu, _opaqueRef);
      if (!_session) {
        throw Error("Must provide `session`");
      }
      if (!_cpu) {
        throw Error("Must provide `host_cpu`");
      }
      if (!_opaqueRef) {
        throw Error("Must provide `opaqueRef`");
      }
      session = _session;
      xenAPI = _xenAPI;
      this.opaqueRef = _opaqueRef;
      this.uuid = _cpu.uuid;
      this.number = _cpu.number;
      this.vendor = _cpu.vendor;
      this.speed = _cpu.speed;
      this.modelname = _cpu.modelname;
      this.family = _cpu.family;
      this.model = _cpu.model;
      this.stepping = _cpu.stepping;
    }

    return Host_CPU;

  })();

  module.exports = Host_CPU;

}).call(this);
