// Generated by CoffeeScript 1.9.1
(function() {
  var Metrics, Promise, debug;

  debug = require('debug')('XenAPI:Metrics');

  Promise = require('bluebird');

  Metrics = (function() {
    var session, xenAPI;

    session = void 0;

    xenAPI = void 0;


    /**
    * Construct Metrics
    * @class
    * @param      {Object}   session - An instance of Session
    * @param      {Object}   metrics - A JSON object representing this Metrics
    * @param      {String}   opaqueRef - The OpaqueRef handle to this Metrics
    * @param      {Object}   xenAPI - An instance of XenAPI
     */

    function Metrics(_session, _metrics, _opaqueRef, _xenAPI) {
      debug("constructor()");
      debug(_metrics, _opaqueRef);
      if (!_session) {
        throw Error("Must provide `session`");
      }
      if (!_metrics) {
        throw Error("Must provide `metrics`");
      }
      if (!_opaqueRef) {
        throw Error("Must provide `opaqueRef`");
      }
      session = _session;
      xenAPI = _xenAPI;
      this.opaqueRef = _opaqueRef;
      this.uuid = _metrics.uuid;
      this.memory_actual = _metrics.memory_actual;
      this.start_time = _metrics.start_time;
      this.VCPUs_number = _metrics.VCPUs_number;
    }

    return Metrics;

  })();

  module.exports = Metrics;

}).call(this);
