// Generated by CoffeeScript 1.9.1
(function() {
  var Network, Promise, debug;

  debug = require('debug')('XenAPI:Network');

  Promise = require('bluebird');

  Network = (function() {
    var session, xenAPI;

    session = void 0;

    xenAPI = void 0;


    /**
    * Construct Network
    * @class
    * @param      {Object}   session - An instance of Session
    * @param      {Object}   network - A JSON object representing this Network
    * @param      {String}   opaqueRef - The OpaqueRef handle to this Network
    * @param      {Object}   xenAPI - An instance of XenAPI.
     */

    function Network(_session, _network, _opaqueRef, _xenAPI) {
      debug("constructor()");
      debug(_network, _opaqueRef);
      if (!_session) {
        throw Error("Must provide `session`");
      }
      if (!_network) {
        throw Error("Must provide `network`");
      }
      if (!_opaqueRef) {
        throw Error("Must provide `opaqueRef`");
      }
      if (!_xenAPI) {
        throw Error("Must provide `xenAPI`");
      }
      session = _session;
      xenAPI = _xenAPI;
      this.opaqueRef = _opaqueRef;
      this.uuid = _network.uuid;
      this.name = _network.name_label;
      this.VIFs = _network.VIFs;
      this.PIFs = _network.PIFs;
      this.MTU = _network.MTU;
    }

    return Network;

  })();

  module.exports = Network;

}).call(this);
