// Generated by CoffeeScript 1.10.0
(function() {
  var PIF, Promise, debug;

  debug = require('debug')('XenAPI:PIF');

  Promise = require('bluebird');

  PIF = (function() {
    var session, xenAPI;

    session = void 0;

    xenAPI = void 0;


    /**
    * Construct PIF
    * @class
    * @param      {Object}   session - An instance of Session
    * @param      {Object}   PIF - A JSON object representing this PIF
    * @param      {String}   opaqueRef - The OpaqueRef handle to this PIF
    * @param      {Object}   xenAPI - An instance of XenAPI.
     */

    function PIF(_session, _PIF, _opaqueRef, _xenAPI) {
      debug("constructor()");
      debug(_PIF, _opaqueRef);
      if (!_session) {
        throw Error("Must provide `session`");
      }
      if (!_PIF) {
        throw Error("Must provide `PIF`");
      }
      if (!_opaqueRef) {
        throw Error("Must provide `opaqueRef`");
      }
      if (!_xenAPI) {
        throw Error("Must provide `xenAPI`");
      }
      session = _session;
      xenAPI = _xenAPI;
      this.opaqueRef = _opaqueRef;
      this.uuid = _PIF.uuid;
      this.name = _PIF.name_label;
      this.IP = _PIF.IP;
      this.gateway = _PIF.gateway;
      this.netmark = _PIF.netmark;
      this.IPv6 = _PIF.IPv6;
      this.ipv6_gateway = _PIF.ipv6_gateway;
      this.MAC = _PIF.MAC;
      this.MTU = _PIF.MTU;
      this.VLAN = _PIF.VLAN;
      this.DNS = _PIF.DNS;
      this.device = _PIF.device;
      this.currently_attached = _PIF.currently_attached;
      this.physical = _PIF.physical;
    }

    return PIF;

  })();

  module.exports = PIF;

}).call(this);
