// Generated by CoffeeScript 1.8.0
(function() {
  var Promise, debug,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  debug = require('debug')('XenAPI:Session');

  Promise = require('bluebird');

  module.exports = (function() {
    function exports(apiClient) {
      this.apiClient = apiClient;
      this.logout = __bind(this.logout, this);
      debug("constructor()");
      if (!this.apiClient) {
        throw Error("Must provide apiClient");
      }
    }

    exports.prototype.logout = function() {
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return reject();
        };
      })(this));
    };

    return exports;

  })();

}).call(this);
