// Generated by CoffeeScript 1.9.1
(function() {
  var Promise, Template, debug,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  debug = require('debug')('XenAPI:Template');

  Promise = require('bluebird');

  Template = (function() {
    var key, session, template, xenAPI;

    key = void 0;

    session = void 0;

    template = void 0;

    xenAPI = void 0;


    /**
    * Construct Template. Very similar to a VM, but not yet set up.
    * @class
    * @param      {Object}   session - An instance of Session
    * @param      {Object}   template - A JSON object representing this Template
    * @param      {String}   key - The OpaqueRef handle to this template
     */

    function Template(_session, _template, _key, _xenAPI) {
      this.provision = bind(this.provision, this);
      this.pushOtherConfig = bind(this.pushOtherConfig, this);
      this.clone = bind(this.clone, this);
      this.getOpaqueRef = bind(this.getOpaqueRef, this);
      this.toJSON = bind(this.toJSON, this);
      debug("constructor()");
      debug(_template);
      if (!_session) {
        throw Error("Must provide `session`");
      }
      if (!_template) {
        throw Error("Must provide `template`");
      }
      if (!(_template.is_a_template && !_template.is_control_domain && _template.uuid)) {
        throw Error("`template` does not describe a valid Template");
      }
      if (!_key) {
        throw Error("Must provide `key`");
      }
      session = _session;
      template = _template;
      key = _key;
      xenAPI = _xenAPI;
      this.uuid = template.uuid;
      this.name = template.name_label;
      this.description = template.name_description;
      this.VIFs = template.VIFs || [];
      this.other_config = template.other_config;
    }

    Template.prototype.toJSON = function() {
      return {
        name: this.name,
        description: this.description
      };
    };


    /**
     * Return the OpaqueRef that represents this Template
     * @return     {String}
     */

    Template.prototype.getOpaqueRef = function() {
      return key;
    };


    /**
     * Clone this Template, creates a new Template
     * @param     {String}  name - A name for the new clone
     * @return    {Promise}
     */

    Template.prototype.clone = function(name) {
      debug("clone()");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          if (!name) {
            return reject("Must provide a name for the clone");
          } else {
            return session.request("VM.clone", [key, name]).then(function(value) {
              debug(value);
              return xenAPI.templateCollection.findOpaqueRef(value).then(function(clonedTemplate) {
                return resolve(clonedTemplate);
              });
            })["catch"](function(e) {
              debug(e);
              return reject(e);
            });
          }
        };
      })(this));
    };

    Template.prototype.pushOtherConfig = function() {
      debug("pushOtherConfig()");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return session.request("VM.set_other_config", [key, _this.other_config]).then(function(value) {
            debug(value);
            return resolve();
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };

    Template.prototype.provision = function() {
      debug("provision()");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return session.request("VM.provision", [key]).then(function(value) {
            debug(value);
            return resolve();
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };

    return Template;

  })();

  module.exports = Template;

}).call(this);
