// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, Template, _, debug,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  debug = require('debug')('XenAPI:Template');

  Promise = require('bluebird');

  _ = require('lodash');

  Template = (function() {
    var session, xenAPI;

    session = void 0;

    xenAPI = void 0;


    /**
    * Construct Template. Very similar to a VM, but not yet set up.
    * @class
    * @param      {Object}   session - An instance of Session
    * @param      {Object}   template - A JSON object representing this Template
    * @param      {String}   opaqueRef - The OpaqueRef handle to this template
    * @param      {Object}   xenAPI - An instance of XenAPI.
     */

    function Template(_session, _template, _opaqueRef, _xenAPI) {
      this.convertToVM = bind(this.convertToVM, this);
      this.setVCPUMax = bind(this.setVCPUMax, this);
      this.setStartupCPUs = bind(this.setStartupCPUs, this);
      this.setMemoryDynamicMin = bind(this.setMemoryDynamicMin, this);
      this.setMemoryDynamicMax = bind(this.setMemoryDynamicMax, this);
      this.setMemoryStaticMin = bind(this.setMemoryStaticMin, this);
      this.setMemoryStaticMax = bind(this.setMemoryStaticMax, this);
      this.getVBDs = bind(this.getVBDs, this);
      this.provision = bind(this.provision, this);
      this.pushOtherConfig = bind(this.pushOtherConfig, this);
      this.clone = bind(this.clone, this);
      this.rename = bind(this.rename, this);
      this.destroy = bind(this.destroy, this);
      this.toJSON = bind(this.toJSON, this);
      debug("constructor()");
      debug(_template, _opaqueRef);
      if (!_session) {
        throw Error("Must provide `session`");
      }
      if (!_template) {
        throw Error("Must provide `template`");
      }
      if (!_opaqueRef) {
        throw Error("Must provide `opaqueRef`");
      }
      if (!_xenAPI) {
        throw Error("Must provide `xenAPI`");
      }
      if (!(_template.is_a_template && !_template.is_control_domain && _template.uuid)) {
        throw Error("`template` does not describe a valid Template");
      }
      session = _session;
      xenAPI = _xenAPI;
      this.opaqueRef = String(_opaqueRef);
      this.uuid = String(_template.uuid);
      this.name = _template.name_label;
      this.description = _template.name_description;
      this.VIFs = _template.VIFs || [];
      this.VBDs = _template.VBDs || [];
      this.other_config = _template.other_config;
      this.ram_minimum = _template.memory_static_max;
      this.vcpu_minimum = _template.VCPUs_max;
      this.is_template = _template.is_a_template;
      this.is_snapshot = _template.is_a_snapshot;
    }

    Template.prototype.toJSON = function() {
      return {
        name: this.name,
        description: this.description
      };
    };

    Template.prototype.destroy = function() {
      debug("destroy()");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return session.request("VM.destroy", [_this.opaqueRef]).then(function(value) {
            return resolve();
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };

    Template.prototype.rename = function(name) {
      debug("rename(" + name + ")");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return session.request("VM.set_name_label", [_this.opaqueRef, name]).then(function(value) {
            return resolve();
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };


    /**
     * Clone this Template, creates a new Template
     * @param     {String}  name - A name for the new clone
     * @return    {Promise}
     */

    Template.prototype.clone = function(name) {
      debug("clone()");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          if (!name) {
            return reject("Must provide a name for the clone");
          } else {
            return session.request("VM.clone", [_this.opaqueRef, name]).then(function(value) {
              debug(value);
              return xenAPI.templateCollection.findOpaqueRef(value).then(function(clonedTemplate) {
                return resolve(clonedTemplate);
              });
            })["catch"](function(e) {
              debug(e);
              return reject(e);
            });
          }
        };
      })(this));
    };

    Template.prototype.pushOtherConfig = function() {
      debug("pushOtherConfig()");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return session.request("VM.set_other_config", [_this.opaqueRef, _this.other_config]).then(function(value) {
            debug(value);
            return resolve();
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };

    Template.prototype.provision = function() {
      debug("provision()");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return session.request("VM.provision", [_this.opaqueRef]).then(function(value) {
            debug(value);
            return xenAPI.vmCollection.findOpaqueRef(_this.opaqueRef).then(function(vm) {
              return resolve(vm);
            });
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };

    Template.prototype.getVBDs = function() {
      debug("getVBDs()");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          var vbdSearchPromises;
          vbdSearchPromises = [];
          _.each(_this.VBDs, function(vbd) {
            var vbdSearchPromise;
            vbdSearchPromise = xenAPI.vbdCollection.findOpaqueRef(vbd);
            return vbdSearchPromises.push(vbdSearchPromise);
          });
          return Promise.all(vbdSearchPromises).then(function(vbdObjects) {
            debug(vbdObjects);
            return resolve(vbdObjects);
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };

    Template.prototype.setMemoryStaticMax = function(max) {
      debug("setMemoryStaticMax(" + max + ")");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return session.request("VM.set_memory_static_max", [_this.opaqueRef, max]).then(function(value) {
            return resolve(value);
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };

    Template.prototype.setMemoryStaticMin = function(min) {
      debug("setMemoryStaticMin(" + min + ")");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return session.request("VM.set_memory_static_min", [_this.opaqueRef, min]).then(function(value) {
            return resolve(value);
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };

    Template.prototype.setMemoryDynamicMax = function(max) {
      debug("setMemoryDynamicMax(" + max + ")");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return session.request("VM.set_memory_dynamic_max", [_this.opaqueRef, max]).then(function(value) {
            return resolve(value);
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };

    Template.prototype.setMemoryDynamicMin = function(min) {
      debug("setMemoryDynamicMin(" + min + ")");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return session.request("VM.set_memory_dynamic_min", [_this.opaqueRef, min]).then(function(value) {
            return resolve(value);
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };

    Template.prototype.setStartupCPUs = function(count) {
      debug("setStartupCPUs(" + count + ")");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return session.request("VM.set_VCPUs_at_startup", [_this.opaqueRef, count]).then(function(value) {
            return resolve(value);
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };

    Template.prototype.setVCPUMax = function(count) {
      debug("setVCPUMax(" + count + ")");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return session.request("VM.set_VCPUs_max", [_this.opaqueRef, count]).then(function(value) {
            return resolve(value);
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };

    Template.prototype.convertToVM = function() {
      debug("convertToVM()");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return session.request("VM.set_is_a_template", [_this.opaqueRef, false]).then(function(value) {
            return xenAPI.vmCollection.findOpaqueRef(_this.opaqueRef).then(function(vm) {
              return resolve(vm);
            });
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };

    return Template;

  })();

  module.exports = Template;

}).call(this);
