// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, VBD, debug,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  debug = require('debug')('XenAPI:VBD');

  Promise = require('bluebird');

  VBD = (function() {
    var session, xenAPI;

    session = void 0;

    xenAPI = void 0;


    /**
    * Construct VBD.
    * @class
    * @param      {Object}   session - An instance of Session
    * @param      {Object}   vbd - A JSON object representing this VBD
    * @param      {String}   opaqueRef - The OpaqueRef handle to this vbd
    * @param      {Object}   xenAPI - An instance of XenAPI.
     */

    function VBD(_session, _vbd, _opaqueRef, _xenAPI) {
      this.getVDI = bind(this.getVDI, this);
      this.push = bind(this.push, this);
      this.insert = bind(this.insert, this);
      this.toJSON = bind(this.toJSON, this);
      debug("constructor()");
      debug(_vbd, _opaqueRef);
      if (!_session) {
        throw Error("Must provide `session`");
      }
      if (!_vbd) {
        throw Error("Must provide `vbd`");
      }
      if (!_opaqueRef) {
        throw Error("Must provide `opaqueRef`");
      }
      if (!_xenAPI) {
        throw Error("Must provide `xenAPI`");
      }
      session = _session;
      xenAPI = _xenAPI;
      this.opaqueRef = _opaqueRef;
      this.uuid = _vbd.uuid;
      this.VM = _vbd.VM;
      this.VDI = _vbd.VDI;
      this.userdevice = _vbd.userdevice;
      this.mode = _vbd.mode;
      this.type = _vbd.type;
      this.empty = _vbd.empty;
    }

    VBD.prototype.toJSON = function() {
      return {
        opaqueRef: this.opaqueRef,
        VM: this.VM,
        VDI: this.VDI,
        userdevice: this.userdevice,
        mode: this.mode,
        type: this.type,
        empty: this.empty,
        bootable: true,
        other_config: {},
        qos_algorithm_type: "",
        qos_algorithm_params: {}
      };
    };

    VBD.prototype.insert = function(vdi) {
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return session.request("VBD.insert", [_this.opaqueRef, vdi]).then(function(value) {
            debug(value);
            return resolve();
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };

    VBD.prototype.eject = function() {
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return session.request("VBD.eject", [_this.opaqueRef]).then(function(value) {
            debug(value);
            return resolve();
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };

    VBD.prototype.push = function() {
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return session.request("VBD.create", [_this.toJSON()]).then(function(value) {
            debug(value);
            return xenAPI.vbdCollection.findOpaqueRef(value).then(function(vbd) {
              return resolve(vbd);
            });
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };

    VBD.prototype.getVDI = function() {
      debug("getVDI()");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return xenAPI.vdiCollection.findOpaqueRef(_this.VDI).then(function(vdi) {
            return resolve(vdi);
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };

    VBD.prototype.setCD = function() {
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return session.request("VBD.set_type", [_this.opaqueRef, 'CD']).then(function(value) {
            debug(value);
            return xenAPI.vbdCollection.findOpaqueRef(value).then(function(vbd) {
              return resolve(vbd);
            });
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };

    VBD.prototype.setDisk = function() {
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return session.request("VBD.set_type", [_this.opaqueRef, 'Disk']).then(function(value) {
            debug(value);
            return xenAPI.vbdCollection.findOpaqueRef(value).then(function(vbd) {
              return resolve(vbd);
            });
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };

    VBD.MODES = {
      RO: "RO",
      RW: "RW"
    };

    VBD.TYPES = {
      CD: "CD",
      DISK: "Disk"
    };

    return VBD;

  })();

  module.exports = VBD;

}).call(this);
