// Generated by CoffeeScript 1.9.1
(function() {
  var Promise, VIF, debug;

  debug = require('debug')('XenAPI:VIF');

  Promise = require('bluebird');

  VIF = (function() {
    var key, session, vif;

    key = void 0;

    session = void 0;

    vif = void 0;


    /**
    	* Construct VIF
    	* @class
    	* @param      {Object}   session - An instance of Session
    	* @param      {Object}   vif - A JSON object representing this VIF
    	* @param      {String}   key - The OpaqueRef handle to this VIF
     */

    function VIF(_session, _vif, _key) {
      debug("constructor()");
      if (!_session) {
        throw Error("Must provide `session`");
      } else {
        session = _session;
      }
      if (!_vif) {
        throw Error("Must provide `vif`");
      }
      vif = _vif;
      if (!_key) {
        throw Error("Must provide `key`");
      } else {
        key = _key;
      }
    }

    return VIF;

  })();

  module.exports = VIF;

}).call(this);
