// Generated by CoffeeScript 1.9.1
(function() {
  var Promise, VM, debug,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  debug = require('debug')('XenAPI:VM');

  Promise = require('bluebird');

  VM = (function() {
    var session, xenAPI;

    session = void 0;

    xenAPI = void 0;


    /**
    * Construct VM
    * @class
    * @param      {Object}   session - An instance of Session
    * @param      {Object}   vm - A JSON object representing this VM
    * @param      {String}   opaqueRef - The OpaqueRef handle to this VM
    * @param      {Object}   xenAPI - An instance of XenAPI.
     */

    function VM(_session, _vm, _opaqueRef, _xenAPI) {
      this.start = bind(this.start, this);
      this.resume = bind(this.resume, this);
      this.suspend = bind(this.suspend, this);
      this.unpause = bind(this.unpause, this);
      this.pause = bind(this.pause, this);
      this.refreshPowerState = bind(this.refreshPowerState, this);
      debug("constructor()");
      debug(_vm, _opaqueRef);
      if (!_session) {
        throw Error("Must provide `session`");
      }
      if (!_vm) {
        throw Error("Must provide `vm`");
      }
      if (!_opaqueRef) {
        throw Error("Must provide `opaqueRef`");
      }
      if (!_xenAPI) {
        throw Error("Must provide `xenAPI`");
      }
      if (!(!_vm.is_a_template && !_vm.is_control_domain && _vm.uuid)) {
        throw Error("`vm` does not describe a valid VM");
      }
      session = _session;
      xenAPI = _xenAPI;
      this.opaqueRef = _opaqueRef;
      this.uuid = _vm.uuid;
      this.name = _vm.name_label;
      this.description = _vm.name_description;
      this.other_config = _vm.other_config;
      this.xenToolsInstalled = !(_vm.guest_metrics === 'OpaqueRef:NULL');
      this.powerState = _vm.power_state;
      this.VIFs = _vm.VIFs;
    }


    /**
     * Refresh the power state of this VM
     * @return     {Promise}
     */

    VM.prototype.refreshPowerState = function() {
      debug("refreshPowerState()");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return session.request("VM.get_power_state", [_this.opaqueRef]).then(function(value) {
            debug(value);
            _this.powerState = value;
            return resolve(value);
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };


    /**
     * Pause this VM. Can only be applied to VMs in the Running state.
     * @return     {Promise}
     */

    VM.prototype.pause = function() {
      debug("pause()");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return _this.refreshPowerState().then(function(currentPowerState) {
            if (currentPowerState !== VM.POWER_STATES.RUNNING) {
              return reject("VM not in " + VM.POWER_STATES.RUNNING + " power state.");
            } else {
              return session.request("VM.pause", [_this.opaqueRef]).then(function(value) {
                return resolve();
              })["catch"](function(e) {
                debug(e);
                return reject(e);
              });
            }
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };


    /**
     * Unpause this VM. Can only be applied to VMs in the Paused state.
     * @return     {Promise}
     */

    VM.prototype.unpause = function() {
      debug("unpause()");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return _this.refreshPowerState().then(function(currentPowerState) {
            if (currentPowerState !== VM.POWER_STATES.PAUSED) {
              return reject("VM not in " + VM.POWER_STATES.PAUSED + " power state.");
            } else {
              return session.request("VM.unpause", [_this.opaqueRef]).then(function(value) {
                return resolve();
              })["catch"](function(e) {
                debug(e);
                return reject(e);
              });
            }
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };


    /**
     * Suspend this VM. Can only be applied to VMs in the Running state.
     * @return     {Promise}
     */

    VM.prototype.suspend = function() {
      debug("suspend()");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return _this.refreshPowerState().then(function(currentPowerState) {
            if (currentPowerState !== VM.POWER_STATES.RUNNING) {
              return reject("VM not in " + VM.POWER_STATES.RUNNING + " power state.");
            } else {
              return session.request("VM.suspend", [_this.opaqueRef]).then(function(value) {
                return resolve();
              })["catch"](function(e) {
                debug(e);
                return reject(e);
              });
            }
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };


    /**
     * Resume this VM. Can only be applied to VMs in the Suspended state.
     * @return     {Promise}
     */

    VM.prototype.resume = function() {
      debug("resume()");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return _this.refreshPowerState().then(function(currentPowerState) {
            var force, startPaused;
            if (currentPowerState !== VM.POWER_STATES.SUSPENDED) {
              return reject("VM not in " + VM.POWER_STATES.SUSPENDED + " power state.");
            } else {
              startPaused = false;
              force = false;
              return session.request("VM.resume", [_this.opaqueRef, startPaused, force]).then(function(value) {
                return resolve();
              })["catch"](function(e) {
                debug(e);
                return reject(e);
              });
            }
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };

    VM.prototype.start = function() {
      debug("start()");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return session.request("VM.start", [_this.opaqueRef, false, false]).then(function(value) {
            return resolve();
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };

    VM.POWER_STATES = {
      HALTED: 'Halted',
      PAUSED: 'Paused',
      RUNNING: 'Running',
      SUSPENDED: 'Suspended'
    };

    VM.DEFAULT_CONFIG = {
      user_version: "0",
      is_a_template: false,
      is_control_domain: false,
      affinity: void 0,
      VCPUs_params: {},
      VCPUs_at_startup: "1",
      actions_after_shutdown: "destroy",
      actions_after_reboot: "restart",
      actions_after_crash: "restart",
      PV_bootloader: "pygrub",
      PV_kernel: void 0,
      PV_ramdisk: void 0,
      PV_args: "console=hvc0",
      PV_bootloader_args: void 0,
      PV_legacy_args: void 0,
      HVM_boot_policy: "",
      HVM_boot_params: {},
      platform: {},
      PCI_bus: void 0,
      other_config: {},
      recommendations: ""
    };

    return VM;

  })();

  module.exports = VM;

}).call(this);
