// Generated by CoffeeScript 1.8.0
(function() {
  var debug;

  debug = require('debug')('APIClient');

  module.exports = (function() {
    function exports(xmlrpc, options) {
      this.options = options;
      debug("constructor()");
      if (!xmlrpc) {
        throw Error("Must provide xmlrpc");
      }
      if (!this.options) {
        throw Error("Must provide options");
      }
    }

    return exports;

  })();

}).call(this);
