// Generated by CoffeeScript 1.8.0
(function() {
  var APIClient, Session, apiClient, session, xmlrpc;

  APIClient = require('./APIClient');

  Session = require('./Models/Session');

  xmlrpc = require('xmlrpc');

  apiClient = new APIClient(xmlrpc);

  session = new Session(apiClient);

  module.exports = function(options) {
    return {};
  };

}).call(this);
