// Generated by CoffeeScript 1.10.0
var APIClient = require('./APIClient');
var ConsoleCollection = require('./ConsoleCollection');
var Consoles = require('./Models/Console');
var GuestMetricsCollection = require('./GuestMetricsCollection');
var GuestMetrics = require('./Models/GuestMetrics');
var MetricsCollection = require('./MetricsCollection');
var Metrics = require('./Models/Metrics');
var NetworkCollection = require('./NetworkCollection');
var Network = require('./Models/Network');
var PoolCollection = require('./PoolCollection');
var Pool = require('./Models/Pool');
var Session = require('./Models/Session');
var SRCollection = require('./SRCollection');
var SR = require('./Models/SR');
var TaskCollection = require('./TaskCollection');
var Task = require('./Models/Task');
var TemplateCollection = require('./TemplateCollection');
var Template = require('./Models/Template');
var VBDCollection = require('./VBDCollection');
var VBD = require('./Models/VBD');
var VDICollection = require('./VDICollection');
var VDI = require('./Models/VDI');
var VIFCollection = require('./VIFCollection');
var VIF = require('./Models/VIF');
var VLANCollection = require('./VLANCollection');
var VLAN = require('./Models/VLAN');
var VMCollection = require('./VMCollection');
var VM = require('./Models/VM');
var Host_CPU = require('./Models/Host_CPU');
var Host_Metrics = require('./Models/Host_Metrics');
var Host = require('./host');
var xmlrpc = require('xmlrpc');

module.exports = function (options) {
  var apiClient,
    consoleCollection,
    guestMetricsCollection,
    metricsCollection,
    networkCollection,
    poolCollection,
    session,
    srCollection,
    taskCollection,
    templateCollection,
    vbdCollection,
    vdiCollection,
    vifCollection,
    vlanCollection,
    vmCollection,
    xenAPI;

  apiClient = new APIClient(xmlrpc, options);
  session = new Session(apiClient);
  xenAPI = {
    session: session
  };
  consoleCollection = new ConsoleCollection(session, Consoles, xenAPI);
  guestMetricsCollection = new GuestMetricsCollection(session, GuestMetrics, xenAPI);
  metricsCollection = new MetricsCollection(session, Metrics, xenAPI);
  networkCollection = new NetworkCollection(session, Network, xenAPI);
  poolCollection = new PoolCollection(session, Pool, xenAPI);
  srCollection = new SRCollection(session, SR, xenAPI);
  taskCollection = new TaskCollection(session, Task, xenAPI);
  templateCollection = new TemplateCollection(session, Template, xenAPI);
  vbdCollection = new VBDCollection(session, VBD, xenAPI);
  vdiCollection = new VDICollection(session, VDI, xenAPI);
  vifCollection = new VIFCollection(session, VIF, xenAPI);
  vlanCollection = new VLANCollection(session, VLAN, xenAPI);
  vmCollection = new VMCollection(session, VM, xenAPI);
  Hosts = new Host(session, Host_CPU, Host_Metrics, xenAPI);
  xenAPI.host = Hosts;
  xenAPI.consoleCollection = consoleCollection;
  xenAPI.guestMetricsCollection = guestMetricsCollection;
  xenAPI.metricsCollection = metricsCollection;
  xenAPI.networkCollection = networkCollection;
  xenAPI.poolCollection = poolCollection;
  xenAPI.srCollection = srCollection;
  xenAPI.taskCollection = taskCollection;
  xenAPI.templateCollection = templateCollection;
  xenAPI.vbdCollection = vbdCollection;
  xenAPI.vdiCollection = vdiCollection;
  xenAPI.vifCollection = vifCollection;
  xenAPI.vlanCollection = vlanCollection;
  xenAPI.vmCollection = vmCollection;
  xenAPI.models = {
    Console: Consoles,
    GuestMetrics: GuestMetrics,
    Metrics: Metrics,
    Network: Network,
    Pool: Pool,
    SR: SR,
    Task: Task,
    VBD: VBD,
    VDI: VDI,
    VIF: VIF,
    VLAN: VLAN,
    VM: VM
  };
  return xenAPI;
};