// Generated by CoffeeScript 1.9.1
(function() {
  var NetworkCollection, Promise, _, debug, minimatch,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  debug = require('debug')('XenAPI:NetworkCollection');

  Promise = require('bluebird');

  minimatch = require('minimatch');

  _ = require('lodash');

  NetworkCollection = (function() {
    var Network, createNetworkInstance, session, xenAPI;

    Network = void 0;

    session = void 0;

    xenAPI = void 0;

    createNetworkInstance = function(network, opaqueRef) {
      if (!(network.other_config && (network.other_config.is_guest_installer_network || network.other_config.is_host_internal_management_network))) {
        return new Network(session, network, opaqueRef, xenAPI);
      }
    };


    /**
    * Construct NetworkCollection
    * @class
    * @param      {Object}   session - An instance of Session
    * @param      {Object}   Network - Dependency injection of the Network class.
    * @param      {Object}   xenAPI - An instance of XenAPI
     */

    function NetworkCollection(_session, _Network, _xenAPI) {
      this.findNamed = bind(this.findNamed, this);
      this.list = bind(this.list, this);
      debug("constructor()");
      if (!_session) {
        throw Error("Must provide session");
      }
      if (!_Network) {
        throw Error("Must provide Network");
      }
      if (!_xenAPI) {
        throw Error("Must provide xenAPI");
      }
      session = _session;
      xenAPI = _xenAPI;
      Network = _Network;
    }


    /**
     * List all Networks
     * @return     {Promise}
     */

    NetworkCollection.prototype.list = function() {
      debug("list()");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return session.request("network.get_all_records").then(function(value) {
            var Networks;
            if (!value) {
              reject();
            }
            debug("Received " + (Object.keys(value).length) + " records");
            Networks = _.map(value, createNetworkInstance);
            return resolve(_.filter(Networks, function(network) {
              return network;
            }));
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };

    NetworkCollection.prototype.findNamed = function(name) {
      debug("findNamed(" + name + ")");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return _this.list().then(function(networks) {
            var matchNetworkName, matches;
            matchNetworkName = function(network) {
              if (minimatch(network.name, name, {
                nocase: true
              })) {
                return network;
              }
            };
            matches = _.map(networks, matchNetworkName);
            return resolve(_.filter(matches, function(network) {
              return network;
            }));
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };

    return NetworkCollection;

  })();

  module.exports = NetworkCollection;

}).call(this);
