// Generated by CoffeeScript 1.9.1
(function() {
  var Promise, TemplateCollection, _, debug, minimatch,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  debug = require('debug')('XenAPI:TemplateCollection');

  Promise = require('bluebird');

  minimatch = require('minimatch');

  _ = require('lodash');

  TemplateCollection = (function() {
    var Template, createTemplateInstance, session, xenAPI;

    session = void 0;

    Template = void 0;

    xenAPI = void 0;

    createTemplateInstance = function(template, key) {
      if (template.is_a_template && !template.is_control_domain) {
        return new Template(session, template, key, xenAPI);
      }
    };


    /**
    * Construct TemplateCollection
    * @class
    * @param      {Object}   session - An instance of Session
    * @param      {Object}   Template - Dependency injection of the Template class.
    * @param      {Object}   XenAPI - Dependecy injection of the XenAPI object.
     */

    function TemplateCollection(_session, _Template, _XenAPI) {
      this.findOpaqueRef = bind(this.findOpaqueRef, this);
      this.findNamed = bind(this.findNamed, this);
      this.list = bind(this.list, this);
      debug("constructor()");
      if (!_session) {
        throw Error("Must provide session");
      }
      if (!_Template) {
        throw Error("Must provide Template");
      }
      if (!_XenAPI) {
        throw Error("Must provide XenAPI");
      }
      session = _session;
      Template = _Template;
      xenAPI = _XenAPI;
    }


    /**
    * List all Templates
    * @return     {Promise}
     */

    TemplateCollection.prototype.list = function() {
      debug("list()");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return session.request("VM.get_all_records").then(function(value) {
            var Templates;
            if (!value) {
              reject();
            }
            debug("Received " + (Object.keys(value).length) + " records");
            Templates = _.map(value, createTemplateInstance);
            return resolve(_.filter(Templates, function(template) {
              return template;
            }));
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };

    TemplateCollection.prototype.findNamed = function(name) {
      debug("findNamed(" + name + ")");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return _this.list().then(function(templates) {
            var matchTemplateName, matches;
            matchTemplateName = function(template) {
              if (minimatch(template.name, name, {
                nocase: true
              })) {
                return template;
              }
            };
            matches = _.map(templates, matchTemplateName);
            return resolve(_.filter(matches, function(template) {
              return template;
            }));
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };

    TemplateCollection.prototype.findOpaqueRef = function(opaqueRef) {
      debug("findOpaqueRef(" + opaqueRef + ")");
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return session.request("VM.get_record", [opaqueRef]).then(function(value) {
            var template;
            if (!value) {
              reject();
            }
            template = createTemplateInstance(value, opaqueRef);
            return resolve(template);
          })["catch"](function(e) {
            debug(e);
            return reject(e);
          });
        };
      })(this));
    };

    return TemplateCollection;

  })();

  module.exports = TemplateCollection;

}).call(this);
